using System.IO;
using System.Runtime.InteropServices;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Imaging;
using Windows.Win32.System.Com;

if (args.Length == 1 && args[0] is "--list" or "-l")
{
    return ListWicDecoders();
}

if (args.Length != 1)
{
    Console.Error.WriteLine("Usage: wic-decoder.exe <image>");
    Console.Error.WriteLine("       wic-decoder.exe --list    enumerate WIC decoders");
    return 2;
}

try
{
    var decoder = BitmapDecoder.Create(
        new Uri(Path.GetFullPath(args[0]), UriKind.Absolute),
        BitmapCreateOptions.PreservePixelFormat,
        BitmapCacheOption.OnLoad);
    if (decoder.Frames.Count == 0)
    {
        throw new InvalidDataException("WIC returned no frames.");
    }

    var encoder = new PngBitmapEncoder();
    encoder.Frames.Add(BitmapFrame.Create(decoder.Frames[0]));
    using var png = new MemoryStream();
    encoder.Save(png);
    Console.OpenStandardOutput().Write(png.GetBuffer(), 0, checked((int)png.Length));
    return 0;
}
catch (Exception error)
{
    Console.Error.WriteLine(error.ToString());
    return 1;
}

// Enumerate every WIC decoder component registered with Windows via
// IWICImagingFactory::CreateComponentEnumerator(WICDecoder).
// WIC bindings (interfaces, IIDs, vtable layouts) are generated by
// Microsoft.Windows.CsWin32 from win32metadata (see NativeMethods.txt).
static unsafe int ListWicDecoders()
{
    try
    {
        HRESULT hr = PInvoke.CoCreateInstance(
            PInvoke.CLSID_WICImagingFactory,
            null,
            CLSCTX.CLSCTX_INPROC_SERVER,
            out IWICImagingFactory factory);
        if (hr.Failed)
        {
            Console.Error.WriteLine($"Failed to create WIC imaging factory: {hr}");
            return 1;
        }

        factory.CreateComponentEnumerator(
            (uint)WICComponentType.WICDecoder,
            (uint)WICComponentEnumerateOptions.WICComponentEnumerateDefault,
            out IEnumUnknown enumerator);

        var decoders = new List<DecoderEntry>();
        var items = new object[1];
        while (true)
        {
            HRESULT next = enumerator.Next(1, items, null);
            if (next.Value != 0 || items[0] is null)
            {
                break; // S_FALSE or error -> end of enumeration
            }

            try
            {
                var info = (IWICComponentInfo)items[0]!;
                var entry = new DecoderEntry();
                Guid clsid = default;
                info.GetCLSID(&clsid);
                entry.Clsid = clsid;

                entry.Name = WicString(info.GetFriendlyName);
                if (entry.Name.Length == 0)
                {
                    entry.Name = $"{{{entry.Clsid}}}";
                }
                entry.Version = WicString(info.GetVersion);

                if (info is IWICBitmapCodecInfo codec)
                {
                    codec.GetContainerFormat(out Guid container);
                    entry.Format = WicConstants.ContainerNames.TryGetValue(container, out string? fmt)
                        ? fmt
                        : $"{{{container}}}";
                    entry.Extensions = WicString(codec.GetFileExtensions);
                }
                decoders.Add(entry);
            }
            catch (COMException)
            {
                // Component that refuses to be inspected; keep enumerating.
            }
            finally
            {
                if (items[0] is not null)
                {
                    Marshal.ReleaseComObject(items[0]);
                    items[0] = null!;
                }
            }
        }

        decoders.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase));
        foreach (var decoder in decoders)
        {
            Console.WriteLine(
                $"{decoder.Name}\t{decoder.Format}\t{decoder.Version}\t{{{decoder.Clsid}}}\t{decoder.Extensions}");
        }
        Console.Error.WriteLine($"{decoders.Count} decoder(s) listed.");
        return 0;
    }
    catch (Exception error)
    {
        Console.Error.WriteLine(error.ToString());
        return 1;
    }
}

// WIC string getters (GetFriendlyName/GetVersion/GetFileExtensions) report the
// required buffer length (including the NUL terminator) when called with a
// zero-sized buffer; read them in two passes through the CsWin32 Span<char>
// extension overloads.
static string WicString(WicStringGetter get)
{
    Span<char> buffer = default;
    get(0, ref buffer, out uint len);
    if (len <= 1)
    {
        return "";
    }

    var chars = new char[len];
    Span<char> span = chars;
    get(len, ref span, out _);
    return new string(chars, 0, checked((int)len - 1));
}

delegate void WicStringGetter(uint cch, ref Span<char> buffer, out uint length);

static class WicConstants
{
    // WICGUID_ContainerFormat* for well-known containers, so the listing stays
    // readable; unknown formats fall back to their raw GUID.
    public static readonly IReadOnlyDictionary<Guid, string> ContainerNames = new Dictionary<Guid, string>
    {
        [new Guid("0AF1D87E-FCFE-4188-BDEB-A7906471CBE3")] = "BMP",
        [new Guid("1B7CFAF4-713F-473C-BBCD-6137425FAEAF")] = "PNG",
        [new Guid("A3A860C4-338F-4C17-919A-FBA4B5628F21")] = "ICO",
        [new Guid("0444F35F-587C-4570-9646-64DCD8F17573")] = "CUR",
        [new Guid("19E4A5AA-5662-4FC5-A0C0-1758028E1057")] = "JPEG",
        [new Guid("163BCC30-E2E9-4F0B-961D-A3E9FDB788A3")] = "TIFF",
        [new Guid("1F8A5601-7D4D-4CBD-9C82-1BC8D4EEB9A5")] = "GIF",
        [new Guid("57A37CAA-367A-4540-916B-F183C5093A4B")] = "JPEG-XR",
        [new Guid("9967CB95-2E85-4AC8-8CA2-83D7CCD425C9")] = "DDS",
        [new Guid("F3FF6D0D-38C0-41C4-B1FE-1F3824F17B84")] = "DNG",
        [new Guid("E1E62521-6787-405B-A339-500715B5763F")] = "HEIF",
        [new Guid("E094B0E2-67F2-45B3-B0EA-115337CA7CF3")] = "WebP",
        [new Guid("FE99CE60-F19C-433C-A3AE-00ACEFA9CA21")] = "RAW",
        [new Guid("FEC14E3F-427A-4736-AAE6-27ED84F69322")] = "JPEG-XL",
    };
}

sealed class DecoderEntry
{
    public string Name = "";
    public string Format = "";
    public string Version = "";
    public string Extensions = "";
    public Guid Clsid;
}
